git:
  depth: 1
env:
  global:
    - CONFIG=opt
    - TEST=objc
    - JOBS=1
jobs:
  include:
    - os: linux
      dist: focal
      group: edge
      arch: arm64-graviton2
      virt: vm
      language: python
      python: "3.6"
    - os: linux
      dist: focal
      group: edge
      arch: arm64-graviton2
      virt: vm
      language: python
      python: "3.7"
    - os: linux
      dist: focal
      group: edge
      arch: arm64-graviton2
      python: "3.8"
      language: python
      virt: vm
    - SCHEME: "RxLibraryUnitTests"
      WORKSPACE: "Tests.xcworkspace" TEST_PATH="src/objective-c/tests" BUILD_ONLY="false"
      INTEROP_SERVER: "false"
      language: objective-c
      osx_image: xcode7.3
    - SCHEME: "InteropTestsLocalSSL"
      WORKSPACE: "Tests.xcworkspace" TEST_PATH="src/objective-c/tests" BUILD_ONLY="false"
      INTEROP_SERVER: "true"
      language: objective-c
      osx_image: xcode7.3
    - SCHEME: "InteropTestsLocalCleartext"
      WORKSPACE: "Tests.xcworkspace" TEST_PATH="src/objective-c/tests"  BUILD_ONLY="false"
      INTEROP_SERVER: "true"
      language: objective-c
      osx_image: xcode7.3
    # TODO(jcanizales): Make tests an app project (instead of library), so the following will work.
    # - SCHEME="InteropTestsRemote"
    #   WORKSPACE="Tests.xcworkspace" TEST_PATH="src/objective-c/tests" BUILD_ONLY="false"
    #   INTEROP_SERVER="true"
    - SCHEME: "HelloWorld"
      WORKSPACE: "HelloWorld.xcworkspace" TEST_PATH="examples/objective-c/helloworld"
      BUILD_ONLY: "true" INTEROP_SERVER="false"
      language: objective-c
      osx_image: xcode7.3
    - SCHEME: "RouteGuideClient"
      WORKSPACE: "RouteGuideClient.xcworkspace" TEST_PATH="examples/objective-c/route_guide"
      BUILD_ONLY: "true" INTEROP_SERVER="false"
      language: objective-c
      osx_image: xcode7.3
    - SCHEME: "AuthSample"
      WORKSPACE: "AuthSample.xcworkspace" TEST_PATH="examples/objective-c/auth_sample"
      BUILD_ONLY: "true" INTEROP_SERVER="false"
      language: objective-c
      osx_image: xcode7.3
    - SCHEME: "Sample"
      WORKSPACE: "Sample.xcworkspace" TEST_PATH="src/objective-c/examples/Sample" BUILD_ONLY="true"
      INTEROP_SERVER: "false"
      language: objective-c
      osx_image: xcode7.3
    - SCHEME: "Sample"
      WORKSPACE: "Sample.xcworkspace" TEST_PATH="src/objective-c/examples/Sample" BUILD_ONLY="true"
      INTEROP_SERVER: "false" FRAMEWORKS="YES"
      language: objective-c
      osx_image: xcode7.3
    - SCHEME: "SwiftSample"
      WORKSPACE: "SwiftSample.xcworkspace" TEST_PATH="src/objective-c/examples/SwiftSample"
      BUILD_ONLY: "true" INTEROP_SERVER="false"
      language: objective-c
      osx_image: xcode7.3
before_install:
  # Until Travis upgrades from Cocoapods 0.39, we need to do it here.
  - if [ "${TRAVIS_CPU_ARCH}" = "arm64" ]; then
      export REPO_ROOT=grpc
      git clone https://github.com/grpc/grpc $REPO_ROOT
      cd $REPO_ROOT
      git submodule update --init
      pip install -r requirements.txt
      GRPC_PYTHON_BUILD_WITH_CYTHON=1 pip install .
    else
      pod --version
      gem uninstall cocoapods -a
      gem install cocoapods -v '1.0.1'
      pod --version
      # Recent pods aren't found if we don't explicitly update Cocoapods' repo.
      pod repo update
      brew install gflags
    fi
install:
  - if [ "${TRAVIS_CPU_ARCH}" != "arm64" ]; then
      pushd $TEST_PATH
      pod install
      popd
    fi
before_script:
  - if [ "${INTEROP_SERVER}" = "true" ]; then
      make interop_server;
      (bins/$CONFIG/interop_server --port=5050 &);
      (bins/$CONFIG/interop_server --port=5051 --use_tls &);
    fi
script:
  - if [ "${TRAVIS_CPU_ARCH}" = "arm64" ]; then
      python setup.py bdist_wheel 
      cd dist
      ls
    fi
  - if [ "${BUILD_ONLY}" = "true" ]; then
      xctool -workspace "$TEST_PATH/$WORKSPACE" -scheme "$SCHEME"
      -sdk iphonesimulator9.3 build;
    else
      xctool -workspace "$TEST_PATH/$WORKSPACE" -scheme "$SCHEME"
      -sdk iphonesimulator9.3 test;
    fi
notifications:
  email: false
